setopt alwaystoend
setopt autocd
setopt autopushd
setopt autoresume
setopt nobgnice
setopt nocaseglob
setopt cdablevars
setopt nocheckjobs
setopt noclobber
setopt combiningchars
setopt completeinword
setopt extendedglob
setopt extendedhistory
setopt noflowcontrol
setopt histexpiredupsfirst
setopt histfindnodups
setopt histignorealldups
setopt histignoredups
setopt histignorespace
setopt histsavenodups
setopt histverify
setopt inc_append_history
setopt share_history
setopt nohup
setopt interactive
setopt interactivecomments
setopt login
setopt longlistjobs
setopt monitor
setopt pathdirs
setopt promptsubst
setopt pushdignoredups
setopt pushdsilent
setopt pushdtohome
setopt rcquotes
setopt sharehistory
setopt zle
