function source_if_exists {
    [[ -s $1 ]] && source $1
}

# Source Prezto.
source_if_exists "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"

source_if_exists $HOME/.work.zsh
source_if_exists $HOME/.funcs.zsh
source_if_exists $HOME/.path.zsh
source_if_exists $HOME/.aliases.zsh
source_if_exists $HOME/.fzf.zsh
source_if_exists $HOME/.zle.zsh

# Use fd for FZF file tree walking instead of find
export FZF_DEFAULT_COMMAND='fd --type f'

# Disable autocorrection suggestions
unsetopt correct
unsetopt correctall
DISABLE_CORRETION="true"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
