source $HOME/.prompt.zsh
[ -f ~/.work.zsh] && source $HOME/.work.zsh
source $HOME/.funcs.zsh
source $HOME/.path.zsh
source $HOME/.aliases.zsh
source $HOME/.fzf.zsh
source $HOME/.zle.zsh
source $HOME/.env.zsh
source $HOME/.setopt.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
