" General Stuff
filetype off
syntax on

set ttyfast
set encoding=utf-8
set rtp+=/usr/local/opt/fzf

source ~/.filetype.vim
source ~/.functions.vim
source ~/.leader.vim
source ~/.mapping.vim
source ~/.plugins.vim
source ~/.ui.vim

" ---------------- File Navigation -----------------
" Allow find commands to search subdirectories
" recursively.
set path+=**

set shortmess+=c
set belloff+=ctrlg

augroup myvimrc
    autocmd!
    autocmd QuickFixCmdPost [^l]* cwindow
    autocmd QuickFixCmdPost l*    lwindow
augroup END

filetype plugin indent on
