" General Stuff
filetype off
syntax on

set ttyfast
set encoding=utf-8
set rtp+=/usr/local/opt/fzf

source ~/.filetype.vim
source ~/.functions.vim
source ~/.leader.vim
source ~/.mapping.vim
source ~/.plugins.vim
source ~/.netrw.vim
source ~/.ui.vim

" ---------------- File Navigation -----------------
" Allow find commands to search subdirectories recursively.
set path+=**

set shortmess+=c
set belloff+=ctrlg

" Insert only one space when joining lines that contain sentence-terminating
" punctuation like `.`.
set nojoinspaces

" If a file is changed outside of vim, automatically reload it without asking
set autoread

" Don't write backup files
set nobackup
set nowritebackup

augroup myvimrc
    autocmd!
    autocmd QuickFixCmdPost [^l]* cwindow
    autocmd QuickFixCmdPost l*    lwindow
augroup END

filetype plugin indent on
