[ -f $ZDOTDIR/work.zsh ] && source $ZDOTDIR/work.zsh

source $ZDOTDIR/prompt.zsh
source $ZDOTDIR/funcs.zsh
source $ZDOTDIR/path.zsh
source $ZDOTDIR/aliases.zsh
source $ZDOTDIR/fzf.zsh
source $ZDOTDIR/zle.zsh
source $ZDOTDIR/env.zsh
source $ZDOTDIR/setopt.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# autoload -Uz compinit && compinit -u
